
<footer>CSC 174:Advanced Front-End Web Design and Development</footer>

<nav class="menu">
	<ul>
		<li><a href="index.php">Home</a></li>
		<li><a href="akshay.php">Akshay</a></li>
		<li><a href="sandesh.php">Sandesh</a></li>
		<li><a href="austin.php">Austin</a></li>
	</ul>
</nav>
</div> <!--.container -->


 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
 <script src="js/menu-highlighter.js"></script>
 <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script></body>

</html>
